hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - root_path=/home/willbo/repos/soundscape-analysis/few_shot_learning
    - set.features=false
    - set.train=true
    - set.eval=false
    - set.train.k_way=10,11,12
  job:
    name: runhydra
    override_dirname: root_path=/home/willbo/repos/soundscape-analysis/few_shot_learning,set.eval=false,set.features=false,set.train.k_way=10,11,12,set.train=true
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /home/willbo/repos/soundscape-analysis/few_shot_learning
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/willbo/repos/soundscape-analysis/few_shot_learning
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
root_path: /home/willbo/repos/soundscape-analysis/few_shot_learning
set:
  features: false
  train: true
  eval: false
  device: cuda
path:
  data_train: /home/willbo/data/dcase/train
  data_test: /home/willbo/data/dcase/test
  train_w: /home/willbo/data/dcase/hfiles/train
  test_w: /home/willbo/data/dcase/hfiles/test
  best_model: /home/willbo/data/dcase/models/best_model.pth
  last_model: /home/willbo/data/dcase/models/last_model.pth
dataset:
  script_path: ${root_path}/datasets/dcase_few_shot_bioacoustic.py
model:
  script_path: ${root_path}/models/prototypical.py
optimizer:
  script_path: ${root_path}/optimizers/adam.py
loss_function:
  script_path: ${root_path}/loss_functions/prototypicalloss.py
features:
  raw: false
  raw_pad: 123.456
  seg_len: 0.2
  hop_seg: 0.05
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
datagen:
  raw: false
  normalize: true
  transpose: true
  balance: true
  ltoi: true
  stratify: true
  random_state: 42
train:
  script_path: ${root_path}/train/prototypical_train.py
  artifacts_path: ${root_path}/datasets/artifacts
  sampler: random
  seed: 42
  num_classes: 15
  n_shot: 5
  n_query: 5
  k_way: 10
  lr: 0.0001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 15
eval:
  script_path: ${root_path}/eval/prototypical_eval.py
  samples_neg: 650
  iterations: 3
  query_batch_size: 8
  negative_set_batch_size: 16
  p_thresh: 0.5
