
#As the scope of the code grows there is most likely need to get more
#organized when it comes to paths/file names/h5 datasets.

root_path: randompath

set:
  features: false
  train: true
  eval: false
  device: cuda

#TODO fix root path stuff, check dcase, assumes data to be in repo in that casse ofc.
#unless over written
path:
  #root: /home/willbo/data/dcase
  #root: C:\Users\martin\Documents\playground
  data_train: /home/willbo/data/dcase/train
  #data_train: C:\Users\martin\Documents\playground\data\train
  data_test: /home/willbo/data/dcase/test
  #data_test: C:\Users\martin\Documents\playground\data\test
  train_w: /home/willbo/data/dcase/hfiles/train
  #train_w: C:\Users\martin\Documents\playground\data\hfiles\train
  test_w: /home/willbo/data/dcase/hfiles/test
  #test_w: C:\Users\martin\Documents\playground\data\hfiles\test
  best_model: /home/willbo/data/dcase/models/best_model.pth
  #best_model: C:\Users\martin\Documents\playground\data\models\best_model.pth
  last_model: /home/willbo/data/dcase/models/last_model.pth
  #last_model: C:\Users\martin\Documents\playground\data\models\last_model.pth

  #Something for model paths.
  #Should be able to save and load models.
  #Load just for testing on a new set etc...

dataset:
  script_path: ${root_path}/datasets/dcase_few_shot_bioacoustic.py

model:
  script_path: ${root_path}/models/prototypical.py

optimizer:
  script_path: ${root_path}/optimizers/adam.py

loss_function:
  script_path: ${root_path}/loss_functions/prototypicalloss.py

features:
  raw: false
  raw_pad: 123.456
  seg_len: 0.200
  hop_seg: 0.050
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256

datagen:
  raw: false
  normalize: true
  transpose: true
  balance: true
  ltoi: true
  stratify: true
  random_state: 42

train:
  script_path: ${root_path}/train/prototypical_train.py
  artifacts_path: ${root_path}/datasets/artifacts 
  sampler: random
  seed: 42
  num_classes: 15
  n_shot: 5
  n_query: 5
  k_way : 10
  lr: 0.0001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 15

eval:
  script_path: ${root_path}/eval/prototypical_eval.py
  samples_neg: 650 #Introduce number for 'all', ex -1
  iterations: 3
  query_batch_size: 8
  negative_set_batch_size : 16
  p_thresh: 0.5